modLoader="javafml" #mandatory
loaderVersion="[38,)"
license="CC0"
issueTrackerURL="https://github.com/AOCAWOL/Alone-And-Together/issues" #optional
[[mods]]
modId="aloneandtogether"
version="${file.jarVersion}"
displayName="Alone And Together"
displayURL="https://github.com/AOCAWOL/Alone-And-Together"
logoFile="aloneandtogether.png"
credits=""
authors="Corgi Taco, YaBoiChips, AOCAWOL"
description='''
'''
[[dependencies.aloneandtogether]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.aloneandtogether]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
